package agent

import (
	"context"
	"fmt"

	"charm.land/fantasy"

	"github.com/lgldsilva/semidx/internal/repotools"
	"github.com/lgldsilva/semidx/internal/search"
	"github.com/lgldsilva/semidx/internal/store"
)

// This file ports the read-only agent tools to fantasy.AgentTool. They are all
// side-effect free, so they are registered as parallel tools (fantasy may run
// them concurrently within a step). Schemas are generated by reflection from
// the typed input structs (json + description tags), replacing the hand-written
// JSON Schema maps in the legacy chat.ToolDef versions.

// ReadTools returns the read-only tool set for a fantasy agent. svc and db may
// be nil when a surface does not expose search/index tools; resolver may be nil
// when git tools are not available (e.g. a remote-only backend).
func ReadTools(svc *search.Service, db store.IndexStore, resolver ScopeResolver) []fantasy.AgentTool {
	var tools []fantasy.AgentTool
	if svc != nil {
		tools = append(tools, newSearchToolF(svc))
	}
	if db != nil {
		tools = append(tools, newIndexStatusToolF(db), newListProjectsToolF(db))
	}
	if resolver != nil {
		tools = append(tools,
			newRepoWorktreesToolF(resolver),
			newRepoBranchesToolF(resolver),
			newRepoStatusToolF(resolver),
		)
	}
	return tools
}

// --- semantic_search ---

type searchInput struct {
	Query   string `json:"query" description:"Natural language query describing what you're looking for"`
	Project string `json:"project,omitempty" description:"Project name or identity (default: auto-detect from workspace)"`
	TopK    int    `json:"top_k,omitempty" description:"Number of results to return (default 5)"`
}

func newSearchToolF(svc *search.Service) fantasy.AgentTool {
	return fantasy.NewParallelAgentTool("semantic_search",
		"Search indexed code and documents by meaning. Returns file:line results with relevance scores. Use for intent/behavior queries, not exact string matching.",
		func(ctx context.Context, in searchInput, _ fantasy.ToolCall) (fantasy.ToolResponse, error) {
			if in.TopK <= 0 {
				in.TopK = 5
			}
			resp, err := svc.Search(ctx, search.Request{Project: in.Project, Query: in.Query, TopK: in.TopK})
			if err != nil {
				return fantasy.NewTextErrorResponse(fmt.Sprintf("search failed: %v", err)), nil
			}
			type hit struct {
				File      string  `json:"file"`
				StartLine int     `json:"start_line"`
				EndLine   int     `json:"end_line"`
				Score     float64 `json:"score"`
				Content   string  `json:"content"`
			}
			hits := []hit{}
			for _, r := range resp.Results {
				hits = append(hits, hit{
					File: r.FilePath, StartLine: r.StartLine, EndLine: r.EndLine,
					Score: r.Score, Content: truncate(r.Content, 200),
				})
			}
			return fantasy.NewTextResponse(JSONResult(map[string]any{
				"results": hits,
				"total":   len(hits),
				"project": resp.Project.Name,
				"keyword": resp.Keyword,
			})), nil
		})
}

// --- index_status ---

type indexStatusInput struct {
	Project string `json:"project,omitempty" description:"Project name or path (default: current directory)"`
}

func newIndexStatusToolF(db store.IndexStore) fantasy.AgentTool {
	return fantasy.NewParallelAgentTool("index_status",
		"Check whether a project is indexed, how many files, and what model. Use before searching if unsure about indexing status.",
		func(ctx context.Context, in indexStatusInput, _ fantasy.ToolCall) (fantasy.ToolResponse, error) {
			if in.Project == "" {
				return fantasy.NewTextErrorResponse("no project specified; call list_projects first to list available projects"), nil
			}
			p, err := db.GetProject(ctx, in.Project)
			if err != nil {
				p, err = db.GetProjectByIdentity(ctx, in.Project)
				if err != nil {
					return fantasy.NewTextErrorResponse(fmt.Sprintf("project %q not found", in.Project)), nil
				}
			}
			count := 0
			if hashes, err := db.ListFileHashes(ctx, p.ID); err == nil {
				count = len(hashes)
			}
			return fantasy.NewTextResponse(JSONResult(map[string]any{
				"name":   p.Name,
				"status": p.Status,
				"model":  p.Model,
				"source": p.SourceType,
				"files":  count,
			})), nil
		})
}

// --- list_projects ---

type listProjectsInput struct{}

func newListProjectsToolF(db store.IndexStore) fantasy.AgentTool {
	return fantasy.NewParallelAgentTool("list_projects",
		"List all indexed projects with their name, identity, source type, indexing status, and embedding model. Call this first when you need to discover what is available.",
		func(ctx context.Context, _ listProjectsInput, _ fantasy.ToolCall) (fantasy.ToolResponse, error) {
			projects, err := db.ListProjects(ctx, 0, 0)
			if err != nil {
				return fantasy.NewTextErrorResponse(fmt.Sprintf("list projects failed: %v", err)), nil
			}
			type proj struct {
				Name       string `json:"name"`
				Identity   string `json:"identity"`
				SourceType string `json:"source_type"`
				Status     string `json:"status"`
				Model      string `json:"model"`
			}
			results := make([]proj, len(projects))
			for i, p := range projects {
				results[i] = proj{
					Name: p.Name, Identity: p.Identity,
					SourceType: p.SourceType, Status: p.Status, Model: p.Model,
				}
			}
			return fantasy.NewTextResponse(JSONResult(map[string]any{
				"projects": results,
				"total":    len(results),
			})), nil
		})
}

// --- repo_worktrees ---

type repoProjectInput struct {
	Project string `json:"project,omitempty" description:"Project name or identity (default: auto-detect from workspace)"`
}

func newRepoWorktreesToolF(resolver ScopeResolver) fantasy.AgentTool {
	return fantasy.NewParallelAgentTool("repo_worktrees",
		"List git worktrees (linked working trees) for a project. Returns path, HEAD commit, branch, and bare flag for each worktree.",
		func(ctx context.Context, in repoProjectInput, _ fantasy.ToolCall) (fantasy.ToolResponse, error) {
			root, err := resolveRoot(ctx, resolver, in.Project)
			if err != nil {
				return fantasy.NewTextErrorResponse(err.Error()), nil
			}
			wts, err := repotools.ListWorktrees(ctx, root)
			if err != nil {
				return fantasy.NewTextErrorResponse(fmt.Sprintf("list worktrees failed: %v", err)), nil
			}
			type wt struct {
				Path   string `json:"path"`
				HEAD   string `json:"head"`
				Branch string `json:"branch"`
				Bare   bool   `json:"bare"`
			}
			results := make([]wt, len(wts))
			for i, w := range wts {
				results[i] = wt{Path: w.Path, HEAD: w.HEAD, Branch: w.Branch, Bare: w.Bare}
			}
			return fantasy.NewTextResponse(JSONResult(map[string]any{
				"worktrees": results,
				"total":     len(results),
			})), nil
		})
}

// --- repo_branches ---

type repoBranchesInput struct {
	Project string `json:"project,omitempty" description:"Project name or identity (default: auto-detect from workspace)"`
	Remote  bool   `json:"remote,omitempty" description:"Include remote branches"`
}

func newRepoBranchesToolF(resolver ScopeResolver) fantasy.AgentTool {
	return fantasy.NewParallelAgentTool("repo_branches",
		"List git branches for a project. Shows local branches by default; include remote branches with remote=true. Each branch shows ahead/behind tracking info.",
		func(ctx context.Context, in repoBranchesInput, _ fantasy.ToolCall) (fantasy.ToolResponse, error) {
			root, err := resolveRoot(ctx, resolver, in.Project)
			if err != nil {
				return fantasy.NewTextErrorResponse(err.Error()), nil
			}
			branches, err := repotools.ListBranches(ctx, root, in.Remote)
			if err != nil {
				return fantasy.NewTextErrorResponse(fmt.Sprintf("list branches failed: %v", err)), nil
			}
			type br struct {
				Name    string `json:"name"`
				Current bool   `json:"current"`
				Remote  bool   `json:"remote"`
				Ahead   int    `json:"ahead"`
				Behind  int    `json:"behind"`
			}
			results := make([]br, len(branches))
			for i, b := range branches {
				results[i] = br{Name: b.Name, Current: b.Current, Remote: b.Remote, Ahead: b.Ahead, Behind: b.Behind}
			}
			return fantasy.NewTextResponse(JSONResult(map[string]any{
				"branches": results,
				"total":    len(results),
			})), nil
		})
}

// --- repo_status ---

func newRepoStatusToolF(resolver ScopeResolver) fantasy.AgentTool {
	return fantasy.NewParallelAgentTool("repo_status",
		"Check git repository status: current branch, dirty state, detached HEAD. Useful before making changes or understanding what branch is active.",
		func(ctx context.Context, in repoProjectInput, _ fantasy.ToolCall) (fantasy.ToolResponse, error) {
			root, err := resolveRoot(ctx, resolver, in.Project)
			if err != nil {
				return fantasy.NewTextErrorResponse(err.Error()), nil
			}
			s, err := repotools.Status(ctx, root)
			if err != nil {
				return fantasy.NewTextErrorResponse(fmt.Sprintf("status failed: %v", err)), nil
			}
			return fantasy.NewTextResponse(JSONResult(map[string]any{
				"current_branch": s.CurrentBranch,
				"detached":       s.Detached,
				"dirty":          s.Dirty,
				"head":           s.HEAD,
			})), nil
		})
}
